services:
  fitness-angular-app:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    command: npm run start:docker:dev
    env_file: .env
    ports:
      - "${DOCKER_PORT}:${LOCAL_PORT}"
    volumes:
      - .:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true